# Generated by Django 4.2.1 on 2023-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='PhotoFiIeName',
        ),
        migrations.AddField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(db_index=True, default='any_name', max_length=100),
        ),
    ]
